INSERT INTO candidates (name, email, gender, phone, address, city, state, country, linkedin, github, salary_expected, status, comments, created_at)
VALUES
('Juan Pérez', 'juan.perez@email.com', 'Masculino', '+34 612345678', 'Calle Mayor 1', 'Madrid', 'Madrid', 'España', 'linkedin.com/in/juanperez', 'github.com/juanperez', '35000 EUR', 'Activo', 'Desarrollador Java con 5 años de experiencia', NOW()),
('María García', 'maria.garcia@email.com', 'Femenino', '+34 623456789', 'Avenida Diagonal 100', 'Barcelona', 'Cataluña', 'España', 'linkedin.com/in/mariagarcia', 'github.com/mariagarcia', '40000 EUR', 'En proceso', 'Especialista en frontend con React', NOW()),
('Carlos Rodríguez', 'carlos.rodriguez@email.com', 'Masculino', '+34 634567890', 'Plaza España 5', 'Sevilla', 'Andalucía', 'España', 'linkedin.com/in/carlosrodriguez', 'github.com/carlosrodriguez', '38000 EUR', 'Activo', 'Experto en bases de datos SQL y NoSQL', NOW()),
('Ana Martínez', 'ana.martinez@email.com', 'Femenino', '+34 645678901', 'Gran Vía 25', 'Valencia', 'Comunidad Valenciana', 'España', 'linkedin.com/in/anamartinez', 'github.com/anamartinez', '42000 EUR', 'Inactivo', 'DevOps engineer con experiencia en AWS', NOW()),
('Pedro Sánchez', 'pedro.sanchez@email.com', 'Masculino', '+34 656789012', 'Calle Príncipe 8', 'Bilbao', 'País Vasco', 'España', 'linkedin.com/in/pedrosanchez', 'github.com/pedrosanchez', '36000 EUR', 'Activo', 'Desarrollador móvil especializado en Android', NOW()),
('Laura Fernández', 'laura.fernandez@email.com', 'Femenino', '+34 667890123', 'Paseo de la Castellana 200', 'Madrid', 'Madrid', 'España', 'linkedin.com/in/laurafernandez', 'github.com/laurafernandez', '39000 EUR', 'En proceso', 'UX/UI designer con portfolio impresionante', NOW()),
('Miguel González', 'miguel.gonzalez@email.com', 'Masculino', '+34 678901234', 'Rambla Catalunya 50', 'Barcelona', 'Cataluña', 'España', 'linkedin.com/in/miguelgonzalez', 'github.com/miguelgonzalez', '41000 EUR', 'Activo', 'Arquitecto de software con experiencia en microservicios', NOW()),
('Carmen López', 'carmen.lopez@email.com', 'Femenino', '+34 689012345', 'Calle Sierpes 20', 'Sevilla', 'Andalucía', 'España', 'linkedin.com/in/carmenlopez', 'github.com/carmenlopez', '37000 EUR', 'Inactivo', 'Data scientist con conocimientos en machine learning', NOW()),
('Javier Ruiz', 'javier.ruiz@email.com', 'Masculino', '+34 690123456', 'Avenida del Puerto 100', 'Valencia', 'Comunidad Valenciana', 'España', 'linkedin.com/in/javierruiz', 'github.com/javierruiz', '43000 EUR', 'Activo', 'Full-stack developer con experiencia en MEAN stack', NOW()),
('Isabel Díaz', 'isabel.diaz@email.com', 'Femenino', '+34 601234567', 'Plaza Circular 3', 'Bilbao', 'País Vasco', 'España', 'linkedin.com/in/isabeldiaz', 'github.com/isabeldiaz', '38000 EUR', 'En proceso', 'QA engineer especializada en pruebas automatizadas', NOW());